# Generated by Django 6.0.1 on 2026-01-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='beauty_city_web.promocode', verbose_name='Промокод'),
        ),
    ]
