# Generated by Django 6.0.1 on 2026-01-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0002_alter_appointment_promo_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-id'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
