# Generated by Django 6.0.1 on 2026-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='masters/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='salons/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='services/', verbose_name='Фото'),
        ),
    ]
