# Generated by Django 6.0.1 on 2026-01-20 15:31

from django.db import migrations


def photo_to_service(Service, service_id, photo_id):
    service = Service.objects.get(id=service_id)
    service.photo = f"services/service{photo_id}.svg"
    service.save()


def add_files_to_models(apps, schema_editor):
    Master = apps.get_model('beauty_city_web', 'Master')
    for id in range(1, 5):
        master = Master.objects.get(id=id)
        master.photo = f"masters/master{id}.svg"
        master.save()

    Salon = apps.get_model('beauty_city_web', 'Salon')
    for id in range(1, 4):
        salon = Salon.objects.get(id=id)
        salon.photo = f"salons/salon{id}.svg"
        salon.save()

    Service = apps.get_model('beauty_city_web', 'Service')
    for id in range(1, 4):
        service = Service.objects.get(id=id)
        service.photo = "services/service1.svg"
        service.save()
    photo_to_service(Service, 4, 6)
    photo_to_service(Service, 5, 3)
    photo_to_service(Service, 6, 2)
    photo_to_service(Service, 7, 5)


def move_backwards(apps, schema_editor):
    Master = apps.get_model('beauty_city_web', 'Master')
    Master.objects.update(photo=None)

    Salon = apps.get_model('beauty_city_web', 'Salon')
    Salon.objects.update(photo=None)

    Service = apps.get_model('beauty_city_web', 'Service')
    Service.objects.update(photo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0004_alter_master_photo_alter_salon_photo_and_more'),
    ]

    operations = [
        migrations.RunPython(add_files_to_models, move_backwards),
    ]
