# Generated by Django 6.0.1 on 2026-01-20 17:04

from django.db import migrations, transaction


def add_reviews(apps, schema_editor):
    Client = Review = apps.get_model('beauty_city_web', 'Client')
    client = Client.objects.all()

    Review = apps.get_model('beauty_city_web', 'Review')

    with transaction.atomic():
        Review.objects.create(
            client=client[1],
            text="Отличное место для красоты, очень доброжелательный и отзывчивый персонал, девочки заботливые, аккуратные и большие профессионалы. Посещаю салон с самого начала, но он не теряет своей привлекательности, как в обслуживании.",
            date="2022-11-12"
        )
        Review.objects.create(
            client=client[2],
            text='Мне всё лень было отзыв писать, но вот "руки дошли". Несколько раз здесь стриглась, мастера звали, кажется, Катя. Все было отлично, приятная молодая женщина и по стрижке вопросов не было)',
            date="2022-11-05"
        )
        Review.objects.create(
            client=client[3],
            text='Делала процедуру микротоки у мастера Светланы . Светлана внимательная, приветливая, ненавязчивая. Рекомендую и мастера, и процедуру. Еще делала бровки у Татьяны , я в восторге , брови просто идеально сдеданы',
            date="2022-10-28"
        )
        Review.objects.create(
            client=client[4],
            text='Сегодня прокололи ушки дочке в этом салоне) Остались довольны обслуживанием и персоналом. Девочки очень приветливые и внимательные . Спасибо большое, всё понравилось)',
            date="2022-11-12"
        )
        Review.objects.create(
            client=client[0],
            text='Отличный салон, сервис на самом высоком уровне, всем мастерам огромное уважение за труд, обязательно вернусь',
            date="2022-11-12"
        )


def move_backwards(apps, schema_editor):
    Review = apps.get_model('beauty_city_web', 'Review')
    Review.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0006_review'),
    ]

    operations = [
        migrations.RunPython(add_reviews, move_backwards),
    ]
