# Generated by Django 6.0.1 on 2026-01-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0007_auto_20260121_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_city_web.master', verbose_name='Мастер'),
            preserve_default=False,
        ),
    ]
