# Generated by Django 6.0.1 on 2026-01-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0009_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='used_count',
        ),
    ]
