# Generated by Django 6.0.1 on 2026-01-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0010_remove_promocode_max_uses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
