# Generated by Django 6.0.1 on 2026-01-23 08:27

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_web', '0011_delete_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Имя должно содержать минимум 2 символа'), django.core.validators.RegexValidator(message='Имя может содержать только буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁa-zA-Z\\s\\-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79179023800', max_length=128, region='RU', verbose_name='Телефон'),
        ),
    ]
